"use client";

import { useState, useEffect } from 'react';
import Link from 'next/link';
import type { NextPage } from 'next';

// Import TypeDoc JSON data (generated by SDK)
import docData from './docs-data.json';

interface TypeDocReflection {
  id: number;
  name: string;
  variant: string;
  kind: number;
  flags: any;
  children?: any[];
  comment?: {
    summary: Array<{ kind: string; text: string }>;
    blockTags?: Array<{ tag: string; text: Array<{ kind: string; text: string }> }>;
  };
  signatures?: Array<{
    parameters?: Array<{
      name: string;
      type?: { name: string; type?: any; };
      comment?: { summary: Array<{ kind: string; text: string }> };
    }>;
    comment?: { summary: Array<{ kind: string; text: string }> };
    type?: { name: string; declaration?: any };
  }>;
  groups?: any[];
  sources?: Array<{ fileName: string; line: number }>;
}

const DocumentationPage: NextPage = () => {
  const [selectedModule, setSelectedModule] = useState<string>('overview');
  const [searchTerm, setSearchTerm] = useState('');

  // Extract modules from TypeDoc data (kind: 2 = Module)
  const modules = (docData as any).children || [];

  // Find the main module (empty name) which contains Shape class
  const mainModule = modules.find((mod: any) => mod.name === '');

  // Extract Shape class (kind: 128 = Class)
  const shapeClass = mainModule?.children?.find((item: any) => item.name === 'Shape');

  // Extract Shape methods (kind: 2048 = Method)
  const allShapeMethods = (shapeClass?.children || []).filter((item: any) => item.kind === 2048);

  // Separate static and instance methods
  const staticMethods = allShapeMethods.filter((m: any) => m.flags?.isStatic);
  const instanceMethods = allShapeMethods.filter((m: any) => !m.flags?.isStatic);

  // Extract functional API
  const functionalModule = modules.find((mod: any) => mod.name === 'functional');
  const functionalExports = functionalModule?.children || [];

  // Extract viewport API
  const viewportModule = modules.find((mod: any) => mod.name === 'viewport');
  const viewportExports = viewportModule?.children || [];

  // Extract SCAD API
  const scadModule = modules.find((mod: any) => mod.name === 'scad');
  const scadExports = scadModule?.children || [];

  // Filter items based on search
  const filterItems = (items: any[]) => {
    if (!searchTerm) return items;
    return items.filter((item: any) =>
      item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.comment?.summary?.some((s: any) => s.text.toLowerCase().includes(searchTerm.toLowerCase()))
    );
  };

  const renderComment = (comment?: any) => {
    if (!comment?.summary) return '';
    return comment.summary.map((s: any) => s.text).join('');
  };

  const renderSignature = (sig?: any) => {
    if (!sig) return '';
    const params = sig.parameters?.map((p: any) => {
      const comment = renderComment(p.comment);
      return `${p.name}${p.type?.name || ''}`;
    }).join(', ') || '';
    return `(${params})`;
  };

  const renderType = (type?: any) => {
    if (!type) return '';
    if (typeof type === 'string') return type;
    if (type?.name) return type.name;
    if (type?.type?.name) return type.type.name;
    return 'any';
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 text-white">
      {/* Header */}
      <div className="bg-black bg-opacity-50 border-b border-blue-500">
        <div className="container mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <h1 className="text-3xl font-bold text-blue-400">
              @moicad/sdk Documentation
            </h1>
            <Link
              href="/"
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
            >
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8">
        <div className="sm:grid lg:grid-cols-4 gap-8">
          {/* Sidebar Navigation */}
          <div className="lg:col-span-1">
            <div className="bg-slate-800 rounded-lg p-4 sticky top-4">
              <h2 className="text-lg font-semibold mb-4 text-blue-400">Navigation</h2>
              <nav className="space-y-2">
                <button
                  onClick={() => setSelectedModule('overview')}
                  className={`block w-full text-left px-3 py-2 rounded transition-colors ${
                    selectedModule === 'overview'
                      ? 'bg-blue-600 text-white'
                      : 'hover:bg-slate-700 text-gray-300'
                  }`}
                >
                  📚 Overview
                </button>
                <button
                  onClick={() => setSelectedModule('shape')}
                  className={`block w-full text-left px-3 py-2 rounded transition-colors ${
                    selectedModule === 'shape'
                      ? 'bg-blue-600 text-white'
                      : 'hover:bg-slate-700 text-gray-300'
                  }`}
                >
                  🎨 Shape API
                </button>
                <button
                  onClick={() => setSelectedModule('functional')}
                  className={`block w-full text-left px-3 py-2 rounded transition-colors ${
                    selectedModule === 'functional'
                      ? 'bg-blue-600 text-white'
                      : 'hover:bg-slate-700 text-gray-300'
                  }`}
                >
                  ⚡ Functional API
                </button>
                <button
                  onClick={() => setSelectedModule('viewport')}
                  className={`block w-full text-left px-3 py-2 rounded transition-colors ${
                    selectedModule === 'viewport'
                      ? 'bg-blue-600 text-white'
                      : 'hover:bg-slate-700 text-gray-300'
                  }`}
                >
                  🖼️ Viewport
                </button>
                <button
                  onClick={() => setSelectedModule('scad')}
                  className={`block w-full text-left px-3 py-2 rounded transition-colors ${
                    selectedModule === 'scad'
                      ? 'bg-blue-600 text-white'
                      : 'hover:bg-slate-700 text-gray-300'
                  }`}
                >
                  📐 OpenSCAD
                </button>
              </nav>

              {/* Search */}
              <div className="mt-6">
                <h3 className="text-lg font-semibold mb-3 text-blue-400">Search</h3>
                <input
                  type="text"
                  placeholder="Search API..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg focus:outline-none focus:border-blue-500 text-white"
                />
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-3">
            {/* Overview Section */}
            {selectedModule === 'overview' && (
              <div className="space-y-8">
                <section className="bg-slate-800 rounded-lg p-6">
                  <h2 className="text-2xl font-bold mb-4 text-blue-400">Quick Start</h2>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold mb-2 text-white">Installation</h3>
                      <pre className="bg-slate-900 p-3 sm:p-4 lg:p-5 rounded-lg overflow-x-auto code-scroll">
                        <code className="text-sm sm:text-base lg:text-lg text-green-400 leading-relaxed">npm install @moicad/sdk</code>
                      </pre>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold mb-2 text-white">Basic Usage - Shape API</h3>
                      <pre className="bg-slate-900 p-3 sm:p-4 lg:p-5 rounded-lg overflow-x-auto code-scroll">
                        <code className="text-sm sm:text-base lg:text-lg text-gray-300 leading-relaxed">{`import { Shape } from '@moicad/sdk';

// Create a simple house
const house = Shape.cube(20)
  .union(Shape.pyramid([20, 20, 15]).translate([0, 0, 10]))
  .color('brown');

// Get geometry for 3D printing
const geometry = house.getGeometry();
console.log('Vertices:', geometry.vertices.length);
console.log('Volume:', house.getVolume());`}</code>
                      </pre>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold mb-2 text-white">Basic Usage - Functional API</h3>
                      <pre className="bg-slate-900 p-3 sm:p-4 lg:p-5 rounded-lg overflow-x-auto code-scroll">
                        <code className="text-sm sm:text-base lg:text-lg text-gray-300 leading-relaxed">{`import { cube, pyramid, translate, union } from '@moicad/sdk';

// Create same house functionally
const house = union(
  cube(20),
  translate([0, 0, 10], pyramid([20, 20, 15]))
);

// Apply color
const coloredHouse = color('brown', house);`}</code>
                      </pre>
                    </div>
                  </div>
                </section>

                <section className="bg-slate-800 rounded-lg p-6">
                  <h2 className="text-2xl font-bold mb-4 text-blue-400">Features</h2>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="space-y-4">
                      <div>
                        <h3 className="text-lg font-semibold text-white">🎯 Fluent API</h3>
                        <p className="text-gray-300">Chainable methods for readable, maintainable code</p>
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">⚡ High Performance</h3>
                        <p className="text-gray-300">10-20x faster than OpenSCAD with manifold-3d engine</p>
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">🔒 Type Safe</h3>
                        <p className="text-gray-300">Full TypeScript support with IntelliSense</p>
                      </div>
                    </div>
                    <div className="space-y-4">
                      <div>
                        <h3 className="text-lg font-semibold text-white">📐 OpenSCAD Compatible</h3>
                        <p className="text-gray-300">98-99% language compatibility for easy migration</p>
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">🎨 3D Viewport</h3>
                        <p className="text-gray-300">Built-in Three.js visualization and rendering</p>
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">📦 Cross Platform</h3>
                        <p className="text-gray-300">Works in browser and Node.js environments</p>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            )}

            {/* Shape API Section */}
            {selectedModule === 'shape' && (
              <div className="space-y-6">
                <section className="bg-slate-800 rounded-lg p-6">
                  <h2 className="text-2xl font-bold mb-4 text-blue-400">Shape Class - Fluent API</h2>
                  <p className="text-gray-300 mb-6">
                    The Shape class provides a fluent interface for 3D modeling. Every method returns a new Shape instance.
                  </p>
                </section>

                {/* Static Methods */}
                <section className="bg-slate-800 rounded-lg p-6">
                  <h3 className="text-xl font-semibold mb-4 text-white">Static Methods (Factory Functions)</h3>
                  <div className="space-y-4">
                    {filterItems(staticMethods).map((method: any, idx: number) => (
                      <div key={idx} className="border-l-4 border-blue-500 pl-4">
                        <h4 className="text-lg font-mono text-blue-400">
                          Shape.{method.name}{renderSignature(method.signatures?.[0])}
                        </h4>
                        <p className="text-gray-300 mt-2">{renderComment(method.comment)}</p>
                        {method.signatures?.[0]?.parameters && (
                          <div className="mt-3 space-y-2">
                            <h5 className="font-semibold text-white">Parameters:</h5>
                            {method.signatures[0].parameters.map((param: any, pidx: number) => (
                              <div key={pidx} className="ml-4">
                                <code className="text-green-400">{param.name}</code>
                                <span className="text-gray-400">: {renderType(param.type)}</span>
                                {renderComment(param.comment) && (
                                  <p className="text-gray-300 text-sm mt-1">- {renderComment(param.comment)}</p>
                                )}
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </section>

                {/* Instance Methods */}
                <section className="bg-slate-800 rounded-lg p-6">
                  <h3 className="text-xl font-semibold mb-4 text-white">Instance Methods (Chainable Operations)</h3>
                  <div className="space-y-4">
                    {filterItems(instanceMethods).map((method: any, idx: number) => (
                      <div key={idx} className="border-l-4 border-green-500 pl-4">
                        <h4 className="text-lg font-mono text-green-400">
                          .{method.name}{renderSignature(method.signatures?.[0])}
                        </h4>
                        <p className="text-gray-300 mt-2">{renderComment(method.comment)}</p>
                        {method.signatures?.[0]?.parameters && (
                          <div className="mt-3 space-y-2">
                            <h5 className="font-semibold text-white">Parameters:</h5>
                            {method.signatures[0].parameters.map((param: any, pidx: number) => (
                              <div key={pidx} className="ml-4">
                                <code className="text-green-400">{param.name}</code>
                                <span className="text-gray-400">: {renderType(param.type)}</span>
                                {renderComment(param.comment) && (
                                  <p className="text-gray-300 text-sm mt-1">- {renderComment(param.comment)}</p>
                                )}
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </section>
              </div>
            )}

            {/* Other sections with simplified rendering */}
            {selectedModule === 'functional' && (
              <div className="space-y-6">
                <section className="bg-slate-800 rounded-lg p-6">
                  <h2 className="text-2xl font-bold mb-4 text-blue-400">Functional API</h2>
                  <div className="space-y-4">
                    {filterItems(functionalExports).map((func: any, idx: number) => (
                      <div key={idx} className="border-l-4 border-purple-500 pl-4">
                        <h4 className="text-lg font-mono text-purple-400">{func.name}</h4>
                        <p className="text-gray-300 mt-2">{renderComment(func.comment)}</p>
                      </div>
                    ))}
                  </div>
                </section>
              </div>
            )}

            {selectedModule === 'viewport' && (
              <div className="space-y-6">
                <section className="bg-slate-800 rounded-lg p-6">
                  <h2 className="text-2xl font-bold mb-4 text-blue-400">3D Viewport</h2>
                  <p className="text-gray-300 mb-6">
                    Built-in Three.js viewport for interactive 3D visualization of CAD models.
                  </p>
                  <div className="space-y-4">
                    {filterItems(viewportExports).map((item: any, idx: number) => (
                      <div key={idx} className="border-l-4 border-cyan-500 pl-4">
                        <h4 className="text-lg font-mono text-cyan-400">{item.name}</h4>
                        <p className="text-gray-300 mt-2">{renderComment(item.comment)}</p>
                      </div>
                    ))}
                  </div>
                </section>
              </div>
            )}

            {selectedModule === 'scad' && (
              <div className="space-y-6">
                <section className="bg-slate-800 rounded-lg p-6">
                  <h2 className="text-2xl font-bold mb-4 text-blue-400">OpenSCAD Support</h2>
                  <div className="space-y-4">
                    {filterItems(scadExports).map((item: any, idx: number) => (
                      <div key={idx} className="border-l-4 border-orange-500 pl-4">
                        <h4 className="text-lg font-mono text-orange-400">{item.name}</h4>
                        <p className="text-gray-300 mt-2">{renderComment(item.comment)}</p>
                      </div>
                    ))}
                  </div>
                </section>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DocumentationPage;
